# -*- coding: utf-8 -*-
# This database is partly copied from the phonopy code.
#  Pure Appl. Chem., Vol. 83, No. 2, pp. 359-396, 2011. is available but the
# following list is from 2006.

# Pure Appl. Chem., Vol. 78, No. 11, pp. 2051-2066, 2006.

# SciPy physical constants are also very useful.
# https://docs.scipy.org/doc/scipy/reference/constants.html

charge = {
    'H' : (1,),
    'D' : (1,),
    'He': (0,),
    'Li': (1,),
    'Be': (2,),
    'B' : (3,),
    'C' : (-4,),
    'N' : (-3,),
    'O' : (-2,),
    'F' : (-1,),
    'Ne': (0,),
    'Na': (1,),
    'Mg': (2,),
    'Al': (3,),
    'Si': (4,),
    'P' : (-3,),
    'S' : (-2,),
    'Cl': (-1,),
    'Ar': (0,),
    'K' : (1,),
    'Ca': (2,),
    'Sc': (3,),
    'Ti': (4,),
    'V' : (5,),
    'Cr': (6,),
    'Mn': (7,),
    'Fe': (2,),
    'Co': (2,),
    'Ni': (2,),
    'Cu': (1,),
    'Zn': (2,),
    'Ga': (3,),
    'Ge': (4,),
    'As': (-3,),
    'Se': (-2,),
    'Br': (-1,),
    'Kr': (0,),
    'Rb': (1,),
    'Sr': (2,),
    'Y' : (3,),
    'Zr': (4,),
    'Nb': (5,),
    'Mo': (6,),
    'Ag': (1,),
    'Cd': (2,),
    'In': (3,),
    'Sn': (4,),
    'Sb': (-3,),
    'Te': (-2,),
    'I' : (-1,),
    'Xe': (0,),
    'Cs': (1,),
    'Ba': (2,),
    'La': (3,),
    'Ce': (4,),
    'Pr': (3,),
    'Nd': (3,),
    'Pm': (3,),
    'Sm': (3,),
    'Eu': (2,),
    'Gd': (3,),
    'Tb': (3,),
    'Dy': (3,),
    'Ho': (3,),
    'Er': (3,),
    'Tm': (3,),
    'Yb': (3,),
    'Lu': (3,),
    'Hf': (4,),
    'Ta': (5,),
    'W' : (6,),
    'Au': (1,),
    'Hg': (2,),
    'Tl': (1,),
    'Pb': (2,),
    'Bi': (3,),
    'Po': (-2,),
    'At': (-1,),
    'Fr': (1,),
    'Ra': (2,),
    'Ac': (3,),
    'Th': (4,),
    'Pa': (5,),
     'U': (6,)
}

unoccupied_bands = {
    'H' : 4,
    'D' : 4,
    'He': 4,
    'Li': 4,
    'Be': 4,
    'B' : 4,
    'C' : 4,
    'N' : 4,
    'O' : 4,
    'F' : 4,
    'Ne': 4,
    'Na': 4,
    'Mg': 4,
    'Al': 4,
    'Si': 4,
    'P' : 4,
    'S' : 4,
    'Cl': 4,
    'Ar': 4,
    'K' : 9,
    'Ca': 9,
    'Sc': 9,
    'Ti': 9,
    'V' : 9,
    'Cr': 9,
    'Mn': 9,
    'Fe': 8,
    'Co': 7,
    'Ni': 6,
    'Cu': 5,
    'Zn': 4,
    'Ga': 4,
    'Ge': 4,
    'As': 4,
    'Se': 4,
    'Br': 4,
    'Kr': 4,
    'Rb': 9,
    'Sr': 9,
    'Y' : 9,
    'Zr': 9,
    'Nb': 9,
    'Mo': 9,
    'Tc': 9,
    'Ru': 8,
    'Rh': 7,
    'Pd': 6,
    'Ag': 5,
    'Cd': 4,
    'In': 4,
    'Sn': 4,
    'Sb': 7,
    'Te': 7,
    'I' : 7,
    'Xe': 7,
    'Cs': 9,
    'Ba': 9,
    'La': 16,
    'Ce': 16,
    'Pr': 16,
    'Nd': 16,
    'Pm': 16,
    'Sm': 16,
    'Eu': 16,
    'Gd': 16,
    'Tb': 15,
    'Dy': 14,
    'Ho': 13,
    'Er': 12,
    'Tm': 11,
    'Yb': 10,
    'Lu': 9,
    'Hf': 10,
    'Ta': 10,
     'W': 10,
    'Re': 9,
    'Os': 8,
    'Ir': 7,
    'Pt': 6,
    'Au': 5,
    'Hg': 5,
    'Tl': 5,
    'Pb': 5,
    'Bi': 5,
    'Po': 5,
    'At': 5,
    'Fr': 9,
    'Ra': 9,
    'Ac': 16,
    'Th': 16,
    'Pa': 16,
     'U': 16}

u_parameter = {
    "Cr": [2, 3],
    "Mn": [2, 3],
    "Fe": [2, 3],
    "Co": [2, 3],
    "Ni": [2, 5],
    "Cu": [2, 5],
    "Zn": [2, 5]}

magmom = {
    "Ti": 2,
     "V": 3,
    "Cr": 4,
    "Mn": 5,
    "Fe": 4,
    "Co": 3,
    "Ni": 2,
    "Cu": 1,
    "Zn": 1,
    "Zr": 2,
    "Nb": 3,
    "Mo": 4,
    "Tc": 5,
    "Ru": 4,
    "Rh": 3,
    "Pd": 2,
    "Ag": 1,
    "Ce": 2,
    "Pr": 3,
    "Nd": 4,
    "Pm": 5,
    "Sm": 6,
    "Eu": 7,
    "Gd": 7,
    "Tb": 6,
    "Dy": 5,
    "Ho": 4,
    "Er": 3,
    "Tm": 2,
    "Yb": 1,
    "Lu": 1,
    "Hf": 2,
    "Ta": 3,
     "W": 4,
    "Re": 5,
    "Os": 4,
    "Ir": 3,
    "Pt": 2,
    "Au": 1,
    "Ac": 1,
    "Th": 2,
    "Pa": 3,
     "U": 4,
    "Np": 5,
    "Pu": 6,
    "Am": 7,
    "Cm": 7,
    "Bk": 6,
    "Cf": 5}
